### ISSUE TITLE
QDP_ENABLE_CUDA_MANAGED_MEMORY doesn't set QDP_USE_CUDA_MANAGED_MEMORY

### ISSUE THREAD

**Issue by mathiaswagner** [JeffersonLab/qdp-jit#11]
The cmake option `QDP_ENABLE_CUDA_MANAGED_MEMORY` is doing nothing as it does not set `QDP_USE_CUDA_MANAGED_MEMORY` which is used in configure_file later.

**Comment by fwinter** [comment]
Fixed. The managed stuff hasn't gotten much attention.
I had added a logic that decides where an allocation goes - pool or native API. See commit message.

**Comment by mathiaswagner** [comment]
Thanks. With upcoming changes to UCX managed looks a lot more promising. I have https://github.com/lattice/quda/pull/1220 for some changes in QUDA and have also done some experiments with prefetching qdp jit allocations.
