### ISSUE TITLE
`LLD_HAS_DRIVER` blocks compilation

### ISSUE THREAD

**Issue by SaltyChiang** [JeffersonLab/qdp-jit#25]
The line here blocks compilation with ROCm based on LLVM 15. It seems that `LLD_HAS_DRIVER` is only available after LLVM 17.

https://github.com/JeffersonLab/qdp-jit/blob/e4362392a20c60a680cfb15d152bb3e533f9a487/lib/qdp_llvm.cc#L183-L185

**Comment by fwinter** [comment]
Yes, I was aware. Fix pushed.
